spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psycho_multi_test
    username: psycho_multi_test_user
    password: 1q2w3e
  liquibase:
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/changelog-master.xml

application:
  errorMapping:
    SUCH_LOGIN_ALREADY_EXISTS:
        code: suchLoginAlreadyExists
        message: такой логин уже существует
    WRONG_LOGIN_FORM:
        code: wrongLoginForm
        message: логин не удволетворяет требованиям. Он должен содержать .....
    WRONG_PASSWORD_FORM:
        code: wrongPasswordForm
        message: логин не удволетворяет требованиям. Он должен содержать .....
    WRONG_CREDENTIALS:
        code: wrongCredentials
        message: неверный логин или пароль
    UNEXPECTED_TEST_EXTERNAL_ID:
        code: unexpectedTestExternalId
        message: Вы запрашиваете несуществующий тест
    UNEXPECTED_LANGUAGE_CODE:
        code: unexpectedLanguageCode
        message: Неверный код языка
    NOT-EMAIL:
        code: notEmail
        message: Указанный Вами адрес электронной почты не является валидным
    UNEXPECTED_GENDER:
        code: unexpectedGender
        message: Пожалуйста, уточните Ваш пол
    UNEXPECTED_ANSWER_EXTERNAL_ID:
        code: unexpectedAnswerExternalId
        message: Неизветный внешний идентификатор ответа
    UNEXPECTED_QUESTION_EXTERNAL_ID:
        code: unexpectedQuestionExternalId
        message: Неизвестный внешний идентификатор вопроса
    END_DATE_IS_BEFORE_START_DATE:
        code: endDateIsBeforeSartDate
        message: Дата окончания должна быть позднее, чем дата начала
    SAME_RESULT_BORDERS:
        code: sameResultBorders
        message: Минимальная и максимальная границы не могут быть идентичны
    NO_SUCH_TEST_IN_SUCH_LANGUAGE:
        code: noSuchTestInSuchLanguage
        message: Простите, вы еще не проходили данный тест на таком языке
    NOT_YOUR_CLIENT:
        code: notYourClient
        message: Это не ваш клиент

  loginRegEx: "[A-Za-z]*"
  passwordRegEx: "[A-Za-z]*"
  emailRegEx: "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$"
  jwtSecret: my-jwt-secret
  authHeader: Authorization
  expirationTime: 600000
  claimForJwt:
    - EXTERNAL_ID
    - EMAIL

  burnOutId: 4e85a270-472c-465b-a9ff-1b59405e12ff

