spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psycho_multi_test
    username: psycho_multi_test_user
    password: 1q2w3e
  liquibase:
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/changelog-master.xml

application:
  errorMapping:
    SUCH_LOGIN_ALREADY_EXISTS:
        code: suchLoginAlreadyExists
        message: такой логин уже существует
    WRONG_LOGIN_FORM:
        code: wrongLoginForm
        message: логин не удволетворяет требованиям. Он должен содержать .....
    WRONG_PASSWORD_FORM:
        code: wrongPasswordForm
        message: логин не удволетворяет требованиям. Он должен содержать .....
    WRONG_CREDENTIALS:
        code: wrongCredentials
        message: неверный логин или пароль
    UNEXPECTED_TEST_EXTERNAL_ID:
        code: unexpectedTestExternalId
        message: Вы запрашиваете несуществующий тест
    UNEXPECTED_LANGUAGE_CODE:
        code: unexpectedLanguageCode
        message: Неверный код языка

  loginRegEx: "[A-Za-z]*"
  passwordRegEx: "[A-Za-z]*"
  jwtSecret: my-jwt-secret
  authHeader: Authorization
  expirationTime: 600000
